# Generated by Django 4.1.4 on 2022-12-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=30)),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("symptom1", models.CharField(max_length=30)),
                ("symptom2", models.CharField(blank=True, max_length=30)),
                ("symptom3", models.CharField(blank=True, max_length=30)),
                ("symptom4", models.CharField(blank=True, max_length=30)),
                ("symptom5", models.CharField(blank=True, max_length=30)),
                ("disease", models.CharField(max_length=30)),
                ("consultDoctor", models.CharField(max_length=30)),
            ],
        ),
    ]
